/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAlert: typeof import('./components/app/AppAlert.vue')['default']
    AppCard: typeof import('./components/app/AppCard.vue')['default']
    AppGrid: typeof import('./components/app/AppGrid.vue')['default']
    AppModal: typeof import('./components/app/AppModal.vue')['default']
    AppPagination: typeof import('./components/app/AppPagination.vue')['default']
    PostFilter: typeof import('./components/posts/PostFilter.vue')['default']
    PostForm: typeof import('./components/posts/PostForm.vue')['default']
    PostItem: typeof import('./components/posts/PostItem.vue')['default']
    PostModal: typeof import('./components/posts/PostModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
